spring:
  data:
    mongodb:
      auto-index-creation: false
      host: localhost
      port: 27017
      username: dbUser
      password: dbPassword
      database: spring_mongo_api_db
      authentication-database: admin

server:
  port: 8080 # Port running Spring Boot app

logging:
  level:
    root: INFO
    '[com.josegomez.spring_mongo_api]': DEBUG

springdoc:
  default-produces-media-type: ''
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
